catch {::common::set_param -quiet hls.xocc.mode csynth};
catch {::common::set_param -quiet hls.xocc.enable_rule_check_client 1};
# 
# Hls run script generated by SDAccel
# 

set xocc_optimize_level 0
open_project krnl_linear_search
set_top krnl_linear_search
add_files "/mnt/project/tl6/example_repo/SDAccel_Examples/acceleration/nearest_neighbor_linear_search/src/krnl_linear_search.cpp" -cflags " -I /mnt/project/tl6/example_repo/SDAccel_Examples/acceleration/nearest_neighbor_linear_search/src "
open_solution solution_OCL_REGION_0
set_part xcku115-flvb2104-2-e
create_clock -period 300MHz -name default
config_sdx -target xocc -optimization_level $xocc_optimize_level
config_dataflow -strict_mode warning
set_clock_uncertainty 27.000000%
config_interface -m_axi_addr64
csynth_design -skip_transform
close_project
puts "Vivado HLS completed successfully"
exit
